defaults:
  - scope:
      path: ""
    values:
      layout: "default"

plugins:
  - jekyll-feed
  - jekyll-sitemap


baseurl: "" # the subpath of your site, e.g. /blog
# url: "https://www.magaramusic.com" # the base hostname & protocol for your site, e.g. http://example.com
url: "https://magaramusic.github.io" # the base hostname & protocol for your site, e.g. http://example.com
logo: /assets/images/icon.png

exclude:
  - .jekyll-cache/
  - Gemfile
  - Gemfile.lock
  - README.md

# SEO and OG global variables
title: Magara
lang: es_ES
email: magara@magaramusic.com
description: >-
  Es sencillo, es sólo amor
twitter:
  username: magaramusic
  card: summary
seo_image: /assets/images/magara_seo.jpg
seo_image_width: 1024
seo_image_height: 1024
